# Generated by Django 4.0.3 on 2022-08-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_cover_alter_instance_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', '-first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='borrowedbook',
            options={'ordering': ['borrowed_date']},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['book']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', '-first_name']},
        ),
    ]
