# Generated by Django 4.0.3 on 2022-08-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=300)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('copies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrowed_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(auto_now=True)),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DhammaEth_Book_Mgt.book')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhamma_id', models.CharField(max_length=40, null=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('borrowed_books', models.ManyToManyField(through='DhammaEth_Book_Mgt.Borrowed_Book', to='DhammaEth_Book_Mgt.book')),
            ],
        ),
        migrations.AddField(
            model_name='borrowed_book',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DhammaEth_Book_Mgt.member'),
        ),
    ]
